### PR TITLE
Added previous roundups.

### PR DESCRIPTION
**Pull request by shurane**
I'll dig through the mailing list and fish out the previous collection of hacks/presentations. Can't just lose them to the ether; lots of cool stuff in there!

### CODE REVIEW

**Comment by shurane** [comment]
@apg, any considerations for adding previous hacks?

**Comment by apg** [comment]
Woah. I have no idea who I missed this!

**Comment by apg** [comment]
Though, at this point, there's a bunch more. See the https://github.com/hackandtell/wrapup repo, which is somewhat up to date I think!

**Comment by shurane** [comment]
@apg whoa that's actually the most nifty thing I've seen. It would be cool to see a link from hackandtell.org to maybe hackandtell.org/wrapup and show the previous hacks by city. I can code something up for that if no one else wants to.

**Comment by apg** [comment]
:+1: There's lots of interesting things possible. I'd like to do more to address this, and I assure you, I've been thinking about it.

**Pull request merged**
